### PR TITLE
added new pipelines

### PR DESCRIPTION
**Pull request by lusu007**
# Description

- Added new pipelines
- Updated Git Hooks
- Updated PR template

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist:

- [x] Checkstyle build-step is running without errors
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by ItsKev — APPROVED** [review]

**Comment by playlegendnet** [comment]
Here is your **BuildScan** from latest pipeline build:

**Comment by playlegendnet** [comment]
Here is your **BuildScan** from latest pipeline build:

**Comment by playlegendnet** [comment]
Here is your **BuildScan** from latest pipeline build:

**Comment by playlegendnet** [comment]
Here is your **BuildScan** from latest pipeline build:

**Review by ItsKev — APPROVED** [review]

**Pull request merged**
